fields:
	general_setttings:
		type: section
		display: General
	owner_email:
		type: text
		display: Owner Email
		instructions: Email address for receiving emails from store
		width: 50
	store_email:
		type: text
		display: Store Email
		instructions: Email address used to send emails to customers and contact them
		width: 50
	store_address:
		type: textarea
		display: Store Address
	order_id_format:
		type: text
		display: Order ID Format
		instructions: Remember to use [id] inside the format
		default: '#[id]'
		width: 50
	order_next_id:
		type: text
		display: Next Order ID
		instructions: Incremental value for every order
		width: 50
		default: 1000
	shipping:
		type: section
		display: Shipping
	shipping_zones:
		type: replicator
		display: Zones
		sets:
			zone:
				display: Zone
				fields:
					name:
						type: text
						display: Name
						width: 25
					countries:
						type: suggest
						display: Countries
						mode: Statamify
						width: 75
					price_rates:
						type: grid
						display: Price Based Rates
						replicator_preview: false
						width: 50
						fields:
							name:
								type: text
								display: Name
							min:
								type: text
								display: Minimum
								validate: numeric
							max:
								type: text
								display: Maximum
								validate: numeric
							rate:
								type: text
								display: Rate
								validate: numeric
							note:
								type: text
								display: Note
						mode: table
						add_row: Add Rate
					weight_rates:
						type: grid
						display: Weight Based Rates
						replicator_preview: false
						width: 50
						fields:
							name:
								type: text
								display: Name
							min:
								type: text
								display: Minimum
								validate: numeric
							max:
								type: text
								display: Maximum
								validate: numeric
							rate:
								type: text
								display: Rate
								validate: numeric
							note:
								type: text
								display: Note
						mode: table
						add_row: Add Rate
			rest:
				display: Rest of world
				instructions: This zone includes any countries not already defined in zones.
				fields:
					name:
						type: text
						display: Name
					price_rates:
						type: grid
						display: Price Based Rates
						replicator_preview: false
						width: 50
						fields:
							name:
								type: text
								display: Name
							min:
								type: text
								display: Minimum
								validate: numeric
							max:
								type: text
								display: Maximum
								validate: numeric
							rate:
								type: text
								display: Rate
								validate: numeric
							note:
								type: text
								display: Note
						mode: table
						add_row: Add Rate
					weight_rates:
						type: grid
						display: Weight Based Rates
						replicator_preview: false
						width: 50
						fields:
							name:
								type: text
								display: Name
							min:
								type: text
								display: Minimum
								validate: numeric
							max:
								type: text
								display: Maximum
								validate: numeric
							rate:
								type: text
								display: Rate
								validate: numeric
						mode: table
						add_row: Add Rate
	shipping_package_weight:
		type: text
		display: Package Weight
		validate: numeric
		instructions: This weight will be added to total weight of the cart
	payments:
		type: section
		display: Payments
	currency:
		type: grid
		display: Currency
		instructions: Set rate to 1 for **default currency**. Use `[symbol]` and `[price]` for formatting the display price
		fields:
			code:
				type: text
				display: Code
			symbol:
				type: text
				display: Symbol
			format:
				type: text
				display: Format
				default: '[symbol] [price]'
			formatPrice:
				type: select
				display: Price Format
				default: 4
				options:
					1: 1,000
					2: 1 000
					3: 1,000.50
					4: 1 000.50
					5: 1 000,50
					6: 1000
					7: 1000.50
					8: 1000,50
			rate:
				type: text
				display: Rate
				validate: numeric
		mode: table
		add_row: Add Currency
	gateway_cheque_start:
		type: fieldblock
		display: Cheque Gateway
	gateway_cheque_info:
		type: textarea
		display: Information
		width: 50
	gateway_cheque_active:
		type: toggle
		display: Enable
		width: 50
	gateway_cheque_end:
		type: fieldblock
		end: true
	gateway_stripe_start:
		type: fieldblock
		display: Stripe Gateway
	gateway_stripe_settings:
		type: array
		display: Stripe Settings
		keys:
			public_key: Public Key
			secret_key: Secret Key
		hide_when:
			gateway_stripe_test: true
		width: 50
	gateway_stripe_settings_test:
		type: array
		display: Stripe Settings - Test Mode
		keys:
			public_key: Test Public Key
			secret_key: Test Secret Key
		hide_when:
			gateway_stripe_test: false
		width: 50
	gateway_stripe_test:
		type: toggle
		display: Test Mode
		width: 25
	gateway_stripe_active:
		type: toggle
		display: Enable
		width: 25
	gateway_stripe_end:
		type: fieldblock
		end: true