taxonomies:
  tags: true
title: Products
fields:
  title:
    type: title
    display: Title
    localizable: true
  listing_image:
    type: hidden
    display: Listing Image
  listing_inventory:
    type: hidden
    display: Listing Inventory
  listing_type:
    type: hidden
    display: Listing Type
  listing_vendor:
    type: hidden
    display: Listing Vendor
  general:
    type: section
    display: General
  class:
    type: select
    display: Class
    options:
      simple: Simple
      complex: Complex
    default: simple
  price:
    type: text
    display: Price
    validate: numeric
    width: 33
  compare_at_price:
    type: text
    display: Compare at price
    width: 33
    validate: numeric
  weight:
    type: text
    display: Weight
    width: 33
    validate: numeric
  sku:
    type: text
    display: SKU
    width: 25
  barcode:
    type: text
    display: Barcode
    width: 25
  inventory:
    type: integer
    display: Inventory
    width: 25
    show_when:
      track_inventory: true
      class: simple
  track_inventory:
    type: toggle
    display: Track Inventory
    width: 25
  variants:
    type: statamify_variants
    display: Variants
    fields:
      - 
        type: text
        display: Option Name
        name: option_name
      - 
        type: tags
        display: Option Values
        name: option_values
    show_when:
      class: complex
  relation:
    type: section
    display: Relation
  type:
    type: collection
    display: Type
    collection:
      - types
    max_items: "1"
    width: 50
  vendor:
    type: collection
    display: Vendor
    collection:
      - vendors
    max_items: "1"
    width: 50
  collections:
    type: collection
    display: Collections
    collection:
      - collections
  images:
    type: section
    display: Images
  image:
    type: assets
    display: Image
    container: main
    folder: /
    max_files: 1
    mode: list
    width: 50
  gallery:
    type: assets
    display: Gallery
    container: main
    folder: /
    mode: list
    width: 50
  content:
    type: section
    display: Content
  description:
    type: redactor
    display: Description
